### ISSUE TITLE
One step is missing with the latest version of the drivers

### ISSUE THREAD

**Issue by cosminmocan** [ryanrudolfoba/SteamDeckWindowsFixForWiFi#1]
In the latest version of the driver, you also get some certs and a bat file which when executed, it installs the certs and lets you install the self signed drivers without needing to exit the normal boot mode.

Also, I don't think you can install these drivers without **driver signature enforcement disable** or without installing the certs, so i think it should not be an optional, new users will be confused.

**Comment by ryanrudolfoba** [comment]
I'll test this later today. Thanks for bringing it up.

**Comment by ryanrudolfoba** [comment]
Updated the document.
