### ISSUE TITLE
Completely tanks performance (both latency & bandwidth)

### ISSUE THREAD

**Issue by Black-Seraph** [ryanrudolfoba/SteamDeckWindowsFixForWiFi#3]
I'm sorry to report that your fix might not be as universal as you think it is.

On both of my Deck's (running Windows 11 Pro 22H2) the packet drop rate sky-rockets after installing this driver, reducing my usual 300+mbit/s bandwidth to <10mbit/s.

This breaks the latency as well of course, as packets get dropped and need to be re-sent multiple times.
The only way I found to fix this issue is to go into the Device Manager, right-click the WiFi adapter, choose Uninstall driver and ticking the box to remove the driver files from the system.

After that I scanned for new hardware which re-installed the 2023 driver I got directly from Realtek, restoring my usual 300+mbit/s bandwidth.

**Comment by ryanrudolfoba** [comment]
sorry about that i got mixed up and uploaded the wrong config file.

i've updated the correct config file and it works as it should -

![image](https://github.com/ryanrudolfoba/SteamDeckWindowsFixForWiFi/assets/98122529/dbac147e-521e-4278-b627-33450f9db5b3)

**Comment by Black-Seraph** [comment]
Can confirm that this fixed it.

I also found out in hindsight that the previous configuration blocked 2.4GHz WiFi access entirely, which is also fixed with the new configuration.
