### ISSUE TITLE
installed new network card after uninstalling driver, causes random windows 11 crashes, Event Viewer ID 7000

### ISSUE THREAD

**Issue by rokavii** [ryanrudolfoba/SteamDeckWindowsFixForWiFi#4]
The RtkWiFiManServ service failed to start due to the following error: 
The system cannot find the file specified.

param1 RtkWiFiManServ param2 %%2 520074006B0057006900460069004D0061006E0053006500720076000000

Binary data:
In Words 0000: 00740052 0057006B 00460069 004D0069
0010: 006E0061 00650053 00760072 0000

In Bytes

0000: 52 00 74 00 6B 00 57 00 R.t.k.W.
0008: 69 00 46 00 69 00 4D 00 i.F.i.M.
0010: 61 00 6E 00 53 00 65 00 a.n.S.e.
0018: 72 00 76 00 00 00 r.v...

I want to stop this from happening as i do not need the service anymore, but when windows randomly calls for it, it causes my computer to crash. I don't know what to do, as nothing works, it doesnt show up in device manager, services in task manager, or anywhere.
Using an ASUS TUF A17, the new network card is an Intel WIFi 6 AX210

**Comment by ryanrudolfoba** [comment]
I've only tested this with a Steam Deck as that is the only machine i have that uses Realtek 8822CE WiFi chip.

I have no idea if this will work with an Asus TUF A17.
